/**
 * @fileoverview Better Auth catch-all API route handler for all authentication endpoints
 *
 * This Next.js API route uses a catch-all route pattern (`[...all]`) to handle ALL authentication
 * requests for the G.A.T.E. Assessment application. Better Auth delegates all auth endpoints through
 * this single handler, which processes both POST and GET requests for various auth operations.
 *
 * **Catch-All Route Pattern:**
 * The `[...all]` directory name in Next.js creates a catch-all route that matches any path under
 * `/api/auth/`. This allows Better Auth to handle all its endpoints through a single route handler:
 * - `/api/auth/sign-in/email` → Handled by POST handler
 * - `/api/auth/sign-up/email` → Handled by POST handler
 * - `/api/auth/session` → Handled by GET handler
 * - `/api/auth/verify-email` → Handled by POST handler
 * - `/api/auth/send-verification-email` → Handled by POST handler
 * - And many more auth endpoints...
 *
 * **How It Works:**
 * 1. Better Auth provides a `handler` function that processes all auth requests
 * 2. `toNextJsHandler()` converts Better Auth's handler to Next.js App Router format
 * 3. The conversion returns both POST and GET named exports for Next.js
 * 4. Next.js routes all `/api/auth/*` requests to this handler based on HTTP method
 * 5. Better Auth internally routes to the correct endpoint handler based on the URL path
 *
 * **Request Routing:**
 * Better Auth automatically handles routing based on the URL path and HTTP method.
 * You don't need to manually configure routes - Better Auth provides them all:
 * - Email/password authentication
 * - Email verification with OTP
 * - Session management
 * - Sign out
 * - OAuth callbacks (if configured)
 *
 * **Configuration:**
 * The auth configuration is defined in `@/lib/auth.ts` and includes:
 * - Email/password authentication with OTP verification
 * - Session management with cookies
 * - Custom user fields (role, firstName, lastName, etc.)
 * - Drizzle ORM database adapter
 *
 * **Security:**
 * - CSRF protection is built into Better Auth
 * - Session cookies are HTTP-only and secure
 * - Email verification is required before login
 * - All endpoints validate request integrity
 *
 * ⚠️ **Important:** Do not add custom logic to this file. This is a pure delegation handler.
 * For custom authentication logic, use middleware, server actions, or authorization guards
 * from `@/lib/authz.ts`.
 *
 * @see {@link @/lib/auth} for Better Auth configuration
 * @see {@link @/lib/authz} for authorization guards
 * @see {@link https://www.better-auth.com/docs/integrations/next-js} Better Auth Next.js integration docs
 */
import { auth } from "@/lib/auth";
import { toNextJsHandler } from "better-auth/next-js";

/**
 * Better Auth HTTP handlers for Next.js App Router.
 *
 * These route handlers are automatically generated by Better Auth's `toNextJsHandler` utility,
 * which converts Better Auth's internal handler to Next.js-compatible POST and GET exports.
 *
 * **POST Handler:**
 * Handles all POST authentication requests including:
 * - Sign in with email/password (`/api/auth/sign-in/email`)
 * - Sign up with email/password (`/api/auth/sign-up/email`)
 * - Email verification with OTP (`/api/auth/verify-email`)
 * - Resend verification email (`/api/auth/send-verification-email`)
 * - Sign out (`/api/auth/sign-out`)
 * - Update user profile
 * - Password reset requests
 *
 * **GET Handler:**
 * Handles all GET authentication requests including:
 * - Get current session (`/api/auth/session`)
 * - OAuth callbacks (if OAuth providers are configured)
 * - Email verification links (if configured)
 *
 * **Usage:**
 * These handlers are used automatically by:
 * - Better Auth client (`@/lib/auth-client.ts`) for frontend auth operations
 * - Server-side auth API (`@/lib/auth.ts`) for session management
 * - OAuth providers for authentication callbacks
 *
 * You should NOT call these endpoints directly. Instead:
 * - **Client-side:** Use hooks from `@/lib/auth-client.ts` (signIn, signUp, useSession, etc.)
 * - **Server-side:** Use auth instance from `@/lib/auth.ts` (auth.api.getSession, etc.)
 * - **Authorization:** Use guards from `@/lib/authz.ts` (requireSession, requireRole, etc.)
 *
 * @see {@link @/lib/auth-client} for client-side authentication hooks
 * @see {@link @/lib/auth} for server-side authentication API
 * @see {@link @/lib/authz} for server-side authorization guards
 */
export const { POST, GET } = toNextJsHandler(auth.handler);
